### ISSUE TITLE
Height of Hexagon

### ISSUE THREAD

**Issue by SvenLauterbach** [web-tiki/responsive-grid-of-hexagons#12]
Hi,
in the customization section in the readme their is a formula for setting the vertical space. In this formula you have to use the height of the hexagon:

> 1/2 height of hexagon

Where do i find the height of the hexagon? In the css there is only a selector for the a tag inside the hexagon with height: 100%

Did you use scss or sass to generate the css file? If yes, it would be great if you could share those files too.

Thank you for your work and help!

**Comment by SvenLauterbach** [comment]
Sorry, didn't saw the "height of hexagon" section

**Comment by SvenLauterbach** [comment]
Anyway, The Sass/Scss files would be cool....

**Comment by poi33** [comment]
There are no Sass/Scss files to my knowledge. When i contribute to repository i always edit the css files directly.

**Comment by web-tiki** [comment]
There is no Sass/Scss files.
