### ISSUE TITLE
On android phone externals hexagons not clickables

### ISSUE THREAD

**Issue by crapoio** [web-tiki/responsive-grid-of-hexagons#13]
Hello,

On my Android mobile, with hexagons displaying in lines 2+1+2+1
I can only click the hexagon alone on his line.
The ones who are 2 per line can't be clicked.

Could You check that please ?

Thank You

OIO

![hex](https://cloud.githubusercontent.com/assets/23585731/20458445/bb9cfb4c-aea5-11e6-9d84-c48c2bf574b7.PNG)

**Comment by web-tiki** [comment]
Hi @crapoio, thx for reporting, I managed to reproduce your issue on android browser. I wont have time to look into it right now though.

**Comment by crapoio** [comment]
Hello Web-tiki,   thank You for your answer. Ok but do You think You'll work on solving this issue ? Sooner or later ? (Hopefully sooner than later.) Thank You. Best Regards.  Crapoio

**Comment by web-tiki** [comment]
@crapoio I have been working on this repo and changed the approach for the hexagon layout. 
I haven't merged them into the master branch yet but they are merged in the demo branch. Can you check the demo here http://web-tiki.github.io/responsive-grid-of-hexagons/ and tell me if the issue is still occuring for you please. 

Hopefully it has been solved with the latest modifications

**Comment by web-tiki** [comment]
@crapoio This browser is now replaced for new devices by chrome for android. It's usage according to [canIuse ](http://caniuse.com/) is very low so I am closing this as issue.

**Comment by crapoio** [comment]
@web-tiki . Sorry for my late reply.  I checked yesterday and it now work on Android. Thanks a lot.

**Comment by web-tiki** [comment]
@controversial great! Thx for the feedback :)

**Comment by controversial** [comment]
@web-tiki Did you mean to mention me, or @crapoio ?

**Comment by web-tiki** [comment]
@controversial sorry, that was my mistake, I wanted to mention @crapoio

**Comment by controversial** [comment]
Ah, ok
