### ISSUE TITLE
hexagon size

### ISSUE THREAD

**Issue by AliDarrudi67** [web-tiki/responsive-grid-of-hexagons#14]
hi
i want to resize the hexagon to smaller shapes and add number of hexa per row.
how to do this?
thanks.

**Comment by web-tiki** [comment]
@ingenuous67 What you want to do can be done by changing the values explained in the "spacing" section (https://github.com/web-tiki/responsive-grid-of-hexagons#spacing ). As your aim is to modify the existing grid, this is not an issue so I am closing it.

**Comment by AliDarrudi67** [comment]
there is no js file!!!

**Comment by web-tiki** [comment]
@ingenuous67  no ther is no JS file because there is no need for one...

**Comment by AliDarrudi67** [comment]
what is m and w in spacing section of document!!!

**Comment by web-tiki** [comment]
@ingenuous67 m and w are explained in the spacing section of the document.
