### ISSUE TITLE
border

### ISSUE THREAD

**Issue by AliDarrudi67** [web-tiki/responsive-grid-of-hexagons#16]
hi
thanks a lot for this plugin.
i have a question???
can i set a border for hexa shapes?
a think like :
http://jamepush.ir/views/site/e.jpg
set a border and remove spaces.

**Comment by web-tiki** [comment]
hi @ingenuous67 
I can't access your link

**Comment by AliDarrudi67** [comment]
check this:
http://hoshmandeng.com/e.jpg

**Comment by web-tiki** [comment]
@ingenuous67 ok, I see. This is possible but pretty hard as the hexagon grid (HTML/CSS) wasn't designed for borders.
I am going to close this as it is not an issue with the code but an alteration of the design.

**Comment by AliDarrudi67** [comment]
i have another question
on mouse hover i want to view an information on hexagon.
see this link:
http://hoshmandeng.com/e2.jpg
how to do this?
