### ISSUE TITLE
How to make hexagons flat-topped 

### ISSUE THREAD

**Issue by Jwbeev** [web-tiki/responsive-grid-of-hexagons#18]
Hi, 

This is a very cool bit of code here. But I am wondering how to make the calculations work so that the hexagons are actually flat-topped (horizontal) rather than pointed upward (vertical). I can't seem to adjust the rotations in a way to make this work.

Rotating the .hex div will change the hexagon's orientation, but getting everything inside the .hexLink div to look right is the tricky part...

**Comment by web-tiki** [comment]
Hi,

This is the same issue as https://github.com/web-tiki/responsive-grid-of-hexagons/issues/9 .
Unfortunatly, it will need to rebuild the grid as the hexagon positioning and creation changes drasticaly. You can check this stackoverflow question though http://stackoverflow.com/questions/10062887/generate-repeating-hexagonal-pattern-with-css3 .
I will close this issue as it isn't an issue related to the code but an alteration of the output.

Regards,
web-tiki
