### ISSUE TITLE
Hexagon area question or so...?

### ISSUE THREAD

**Issue by xrobachok** [web-tiki/responsive-grid-of-hexagons#19]
```
.hexLink {
background: red;
}
```
Just add this code and see what happened (some time you can see red color). It seems like hexagons not "pixel perfect".

**Comment by web-tiki** [comment]
Hi. 
Can you please add a screenshot of the issue and specify what browser you are using.
Regards,
web-tiki

**Comment by xrobachok** [comment]
http://i.imgur.com/683D18t.png now you see red color in hexagons?
Chrome 58 (latest stable release), Windows 10.

**Comment by web-tiki** [comment]
Thx for the info, I'll look into this

**Comment by web-tiki** [comment]
@xrobachok This is a rendering bug, the overflow on the `.hexLink` element isn't working. I have not found a workaround for it yet.
