### ISSUE TITLE
equation of margin?

### ISSUE THREAD

**Issue by e-cloud** [web-tiki/responsive-grid-of-hexagons#2]
@web-tiki , would you mind showing the **equation of margin** as below?

```
#categories li:nth-child(9n+6),
#categories li:nth-child(9n+7), 
#categories li:nth-child(9n+8), 
#categories li:nth-child(9n+9) {
    margin-top: -4.2%;
    margin-bottom: -4.2%;
    -webkit-transform: translateX(50%) rotate(-60deg) skewY(30deg);
            transform: translateX(50%) rotate(-60deg) skewY(30deg);
  }

```

**Comment by e-cloud** [comment]
and i find that the sloping gaps are wider than the horizontal gaps

**Comment by web-tiki** [comment]
@e-cloud I'm going to tweak those margins and make some decent doc on this repo this afternoon.

**Comment by web-tiki** [comment]
@e-cloud I added an explanation of the vertical spacing calculation + fixed the verticval spacing visual issue

**Comment by e-cloud** [comment]
i think the margin equation is a bit strange

```
m = - h + h * cos(60deg) + sin (45deg)
```

i can't find any angle involved with **45deg**

IMHO, my equation is below

```
m = - h + h * cos(60deg) + 1 * sin (60deg)
```

because in the center of three hexgon, 
![qq 20151220104831](https://cloud.githubusercontent.com/assets/5255354/11916249/54c3ee52-a709-11e5-8545-2aa80ca0121a.png)

there is a regular triangle,  the length of its edge is quite the space between hexgon

**Comment by web-tiki** [comment]
@e-cloud good point I got muddled up with that angle. It is 60 deg.

I'm reopening the issue and will make the changes.

**Comment by web-tiki** [comment]
@e-cloud in fact it isn't sin(60deg) it is cos(30deg) see the following : 

![hex spacing](https://cloud.githubusercontent.com/assets/8065876/11917812/d5f924f2-a717-11e5-9f98-f7c3496640ce.png)

x is the vertical spacing we are looking for and s is the spacing we want. the angle between both is 30deg so 
```
cos(30deg) = x / s 
```
so
```
x = s * cos(30deg)
```

the equation to calculate the vertical margin is 

```
m = - h + h * cos(60deg) + 1 * cos (30deg)
```

**Comment by web-tiki** [comment]
Done, @e-cloud  thx for reporting and helping get this fixed.

**Comment by e-cloud** [comment]
in fact, i want to thank you as your wonderful work inspires what i'm working on :smile:

**Comment by web-tiki** [comment]
@e-cloud nice :)
what are you working on? I would love to see.
