### ISSUE TITLE
[Question] Using the hexagrid in a div

### ISSUE THREAD

**Issue by MinThaMie** [web-tiki/responsive-grid-of-hexagons#23]
I'm using your grid as follows:

`<div id="honeycomb"><ul id="hexGrid"></ul></div>`

and then dynamically append the list items with jquery like this: `$("#hexGrid").append('<li class="hex"><a class="hexIn" href="#"><img src=' + data[i].photo + ' alt="" />' +
                              '<h1>' + data[i].employee_id + '</h1><p></p></a></li>');`

And even though the parent div is larger the hexGrid does not stretch as nicely as in your examples. I did not change any code and took the code from this codepen: https://codepen.io/web-tiki/pen/wWGeEM

Hopefully one of you can help me to figure this out, because it looks not so nice now :(
![screen shot 2017-08-09 at 16 42 08](https://user-images.githubusercontent.com/5811560/29127701-1f1bdd0a-7d22-11e7-8260-88676109f8d2.png)

**Comment by poi33** [comment]
I created this example: https://jsfiddle.net/w1o7kzow/2/
And there does not seem to be anything wrong with the code.
Maybe there is some css that affects the "honeycomb" id?

**Comment by web-tiki** [comment]
@MinThaMie the behaviour you see is the normal behaviour. If you stretch width of the result window in the codepen, you will see that the grid adjusts to 2-3 hexagons per row. As you only have 4, and the fifth one is missing, it looks like the grid isn't centered.

I suppose (you haven't explained what you want) that you want the grid to always display 1-2 hexagons per row. For this, you just need to modify the CSS:

- move the content of the second media query out of it (`@media (max-width: 1200px) {  /* <- 4-3  hexagons per row */`)
-  delete the second media query  with all it's content  (`@media (min-width:1201px) {  /* <- 2-3  hexagons per row */`)

**Comment by MinThaMie** [comment]
Thanks for the answers, for some reason the extra div broke the height of the `<ul>`. Thanks for the quick response :) I love this repo!

**Comment by web-tiki** [comment]
On a side note, you should use the CSS from the repo rather than the one on Codepen as it isn't maintained there.

**Comment by MinThaMie** [comment]
The repo CSS results in this: 
![screen shot 2017-08-10 at 11 31 16](https://user-images.githubusercontent.com/5811560/29164386-830aaab0-7dbf-11e7-9d5e-a3f8d4450b32.png)

In safari and firefox

**Comment by poi33** [comment]
@web-tiki did we ever test the grid in safari?
Are there some -prefixes we are missing?

**Comment by web-tiki** [comment]
@poi33 the grid has been successfully tested on safari and firefox and no prefixes are missing.
@MinThaMie have you tested the repo demo [here](http://web-tiki.github.io/responsive-grid-of-hexagons/)? And what versions on firefox and safari have you seen that result on?

**Comment by MinThaMie** [comment]
I'm really sorry. I managed to forget one crucial class :(

**Comment by web-tiki** [comment]
No problem.
