### ISSUE TITLE
Fixed height and width hexagons

### ISSUE THREAD

**Issue by oyeanuj** [web-tiki/responsive-grid-of-hexagons#26]
Hi folks! Firstly, thank you for open sourcing this - it is super helpful. There aren't too many resources combining hexagon and images.

Just one question - for my usecase, I was using your technique of displaying the image in a hexagon without the grid feature. I needed to specify a fixed width and height for the image. So, for my example I specifed the width and height both as `.hex` as 128px. However, I noticed that `.hexIn` and the image exceed those sizes (apart from the sizing, image displays great).

Here is a screenshot:
![image](https://user-images.githubusercontent.com/9633371/37372180-1fcda754-26cf-11e8-8d8b-610f3786c89d.png)

Any ideas on how might I achieve with the markup and styling that you provide?

Thank you!

**Comment by web-tiki** [comment]
Hi @oyeanuj I don't think I understand your issue correctly. 
The .`hex`  element shouldn't be given a height. The height is given by the `:after` pseudo element and `padding-bottom`.
Can you elaborate on your issue please. A live example would also be great.

**Comment by web-tiki** [comment]
Hello again @oyeanuj have you managed to find a solution to your issue? If not, I'd be glad to help you but as stated in my last comment, I need more info.

**Comment by web-tiki** [comment]
Because of the lack of information and feedback, I am closing this issue. Feel free to reopen it if you have more info about your issue.

**Comment by oyeanuj** [comment]
@web-tiki Thank you for the response and sorry for the delay, I missed the Github notifications somehow. Here is an example of that - https://codesandbox.io/s/4qn3mpn914

I do have the `:after` pseudo-element as well as the padding-bottom but the image either gets skewed or goes past the parent's height.

Thoughts?

**Comment by web-tiki** [comment]
@oyeanuj this sin't an issue with the code from this repo. You have added some CSS (max-width and max-height) on the image. Remove those and your image will keep it's aspect ratio.
