### ISSUE TITLE
How to Replace images? <img src="https://farm8.staticflickr.com/7187/6895047173_d4b1a0d798.jpg" alt="" />

### ISSUE THREAD

**Issue by efitgo** [web-tiki/responsive-grid-of-hexagons#28]
When I attempt to replace images in hexagon (in responsive grid code) with images from my local file directory, the hexagon no longer will display in browser. What can I do to overcome this issue?
Thank you
GFiggins

**Comment by web-tiki** [comment]
Hello @efitgo,
Can you share your code and the image you are trying to use please?

**Comment by efitgo** [comment]
Hi web-tiki,

I greatly appreciate your response and help with the code -

   1. Is there a way to use locally stored images in hexagon grid and
   opposed to using images stored with online providers like
   shutterstock/flickr?  I have several clinical education type images I plan
   to develop that are not found in shutter/flickr and will need to update
   these continuously as subjects evolve.
   2. Is there a way to add URL to hexagon title subject lines? When I add
   link to the hexagon image and/or subject line, the Hexagon disappears or
   loose form when displayed in browser.



   - The goal is to provide a resource page tool using hexagon grid layout
   using custom tile images and custom subject lines that link each hexagon
   subject lines to pages within main site.  Will initially display something
   like this:

[image: image.png]

   - When hover over on main subject line in hexagon, the secondary subject
   lines will display.
   - When hexagon is click will go to linked page:

[image: image.png]


*Here is the edited html:*
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="hexagon5.css">
    <link href='https://fonts.googleapis.com/css?family=Raleway:300'
rel='stylesheet' type='text/css'>
  </head>
  <body>
    <ul id="hexGrid">
      <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="#">
            <a href="https://ceitraining.org/resources/hiv/"
target="_blank"><img src="
https://cdn.stocksnap.io/img-thumbs/960w/3ULPMX0SPES.jpg" alt="hiv" /></a>
            <h1>HIV</h1>
            <p>HIV Resources</p>
          </a>
        </div>
      </li>
      <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="#">
            <img src="
https://farm5.staticflickr.com/4144/5053682635_b348b24698.jpg" alt="" />
            <h1>STD</h1>
            <p>STD Resources</p>
          </a>
        </div>
      </li>
      <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="#">
            <img src="
https://farm3.staticflickr.com/2827/10384422264_d9c7299146.jpg" alt="" />
            <h1>HCV</h1>
            <p>HCV Resources</p>
          </a>
        </div>
      </li>
      <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="#">
            <img src="
https://farm7.staticflickr.com/6217/6216951796_e50778255c.jpg" alt="" />
            <h1>This is a title</h1>
            <p>Some sample text about the article this hexagon leads to</p>
          </a>
        </div>
      </li>
      <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="#">
            <img src="
https://farm7.staticflickr.com/6083/6055581292_d94c2d90e3.jpg" alt="" />
            <h1>This is a title</h1>
            <p>Some sample text about the article this hexagon leads to</p>
          </a>
        </div>
      </li>
      <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="#">
            <img src="
https://farm3.staticflickr.com/2827/10384422264_d9c7299146.jpg" alt="" />
            <h1>This is a title</h1>
            <p>Some sample text about the article this hexagon leads to</p>
          </a>
        </div>
      </li>
      <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="#">
            <img src="
https://farm8.staticflickr.com/7187/6895047173_d4b1a0d798.jpg" alt="" />
            <h1>This is a title</h1>
            <p>Some sample text about the article this hexagon leads to</p>
          </a>
        </div>
      </li>
      <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="#">
            <img src="
https://farm3.staticflickr.com/2878/10944255073_973d2cd25c.jpg" alt="" />
            <h1>This is a title</h1>
            <p>Some sample text about the article this hexagon leads to</p>
          </a>
        </div>
      </li>
      <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="#">
            <img src="
https://farm9.staticflickr.com/8461/8048823381_0fbc2d8efb.jpg" alt="" />
            <h1>This is a title</h1>
            <p>Some sample text about the article this hexagon leads to</p>
          </a>
        </div>
      </li>
    </ul>
  </body>
</html>

*Here is CSS: *
* {
  margin: 0;
  padding: 1;
}
body {
  background: rgb(823,858,823);
}
#hexGrid {
  display: grid;
  grid-gap:129px;
  grid-template-columns: repeat(10,1fr);
  width: 80%;
  margin: 0 auto;
  font-family: 'Raleway', sans-serif;
  font-size: 14px;
  list-style-type: none;
  overflow:hidden;
}

.hex {
  grid-column-end: span 2;
  position: relative;
  visibility:hidden;
  outline:1px solid transparent; /* fix for jagged edges in FF on hover
transition */
}
.hex::after{
  content:'';
  display:block;
  padding-bottom: -70.602%;  /* =  100 / tan(60) * 1.5 */
}
.hexIn{
  position: absolute;
  width:100%;
  padding-bottom: 115.470%; /* =  width / sin(60) */
  overflow: hidden;
  visibility: hidden;
  outline:1px solid transparent; /* fix for jagged edges in FF on hover
transition */
  -webkit-transform: rotate3d(0,0,1,-90deg) skewY(30deg);
      -ms-transform: rotate3d(0,0,1,-90deg) skewY(30deg);
          transform: rotate3d(0,0,1,-90deg) skewY(30deg);
}
.hexIn * {
  position: absolute;
  visibility: visible;
  outline:1px solid transparent; /* fix for jagged edges in FF on hover
transition */
}
.hexLink {
  display:block;
  width: 100%;
  height: 100%;
  text-align: center;
  color: #fff;
  overflow: hidden;
  -webkit-transform: skewY(-30deg) rotate3d(0,0,1,60deg);
      -ms-transform: skewY(-30deg) rotate3d(0,0,1,60deg);
          transform: skewY(-30deg) rotate3d(0,0,1,60deg);
}

/*** HEX CONTENT
**********************************************************************/
.hex img {
  left: -100%;
  right: -100%;
  width: auto;
  height: 100%;
  margin: 0 auto;
  -webkit-transform: rotate3d(0,0,0,0deg);
      -ms-transform: rotate3d(0,0,0,0deg);
          transform: rotate3d(0,0,0,0deg);
}

.hex h1, .hex p {
  width: 100%;
  padding: 5%;
  box-sizing:border-box;
  background-color: rgba(0, 0, 337, 0.8);
  font-weight: 300;
  -webkit-transition:  -webkit-transform .2s ease-out, opacity .3s ease-out;
          transition:          transform .2s ease-out, opacity .3s ease-out;
}
.hex h1 {
  bottom: 50%;
  padding-top:50%;
  font-size: 1.5em;
  z-index: 1;
  -webkit-transform:translate3d(0,-100%,0);
      -ms-transform:translate3d(0,-100%,0);
          transform:translate3d(0,-100%,0);
}
.hex h1::after {
  content: '';
  position: absolute;
  bottom: 0;
  left: 45%;
  width: 10%;
  text-align: center;
  border-bottom: 1px solid #fff;
}
.hex p {
  top: 50%;
  padding-bottom:50%;
  -webkit-transform:translate3d(0,100%,0);
      -ms-transform:translate3d(0,100%,0);
          transform:translate3d(0,100%,0);
}


/*** HOVER EFFECT
**********************************************************************/
.hexLink:hover h1, .hexLink:focus h1,
.hexLink:hover p, .hexLink:focus p{
  -webkit-transform:translate3d(0,0,0);
      -ms-transform:translate3d(0,0,0);
          transform:translate3d(0,0,0);
}

/*** HEXAGON SIZING AND EVEN ROW INDENTATION
*****************************************************************/

@media (min-width:901px) { /* <- 5-4  hexagons per row */
  #hexGrid{
    padding-bottom: 15.4%;
  }
  .hex:nth-child(9n+3){ /* first hexagon of even rows */
    grid-column-start: 2;
  }
}

@media (max-width: 900px) and (min-width:601px) { /* <- 4-3  hexagons per
row */
  #hexGrid{
    padding-bottom: 5.4%;
  }
  .hex:nth-child(3n+3){ /* first hexagon of even rows */
    grid-column-start: 4;
  }
}

@media (max-width: 600px) and (min-width:301px) { /* <- 3-2  hexagons per
row */
  #hexGrid{
    padding-bottom: 5.4%;
  }
  .hex:nth-child(3n+4){ /* first hexagon of even rows */
    grid-column-start: 1;
  }
}

@media (max-width: 300px) { /* <- 2-1  hexagons per row */
#hexGrid{
  grid-template-columns: repeat(4,1fr);
  padding-bottom: 11.2%;
  grid-gap:5px;
}
.hex:nth-child(3n+3){ /* first hexagon of even rows */
  grid-column-start: 2;
}
}

@media (max-width: 100px) {
  #hexGrid {
      font-size: 13px;
  }
}

**Comment by poi33** [comment]
@web-tiki https://jsfiddle.net/9ewo4L2x/ tried to copy the code to a fiddle.

**Comment by efitgo** [comment]
this is what I see in browser:
[image: image.png]

Would you have any code suggestion to replace images with those store
locally in my directory? and add links to hexagon subjects?

I am able to move the hexagons on page but adding image/links seem to not
work?
thank you.

**Comment by web-tiki** [comment]
@efitgo the image url (https://cdn.stocksnap.io/img-thumbs/960w/3ULPMX0SPES.jpg) you used in the first hexagon doesn't exist (at least, I can't access it with the url you provide) so it isn't displayed. That is why the hexagon disapears. 
On a side note, there is a white-psace before the url in the `src` attribute. That might be a typo.

Adding local images is possible and works the same.

For the link, you should use the existing one and replace the `href` attribute. Note that nesting a `<a>` tag inside andther `<a>` tag is invalid in HTML. So you shouldn't add another one inside the existing one.

Regards,

**Comment by efitgo** [comment]
Thank you so very much my friend!  Did the adjustments and working well now!
Best regards,
