### ISSUE TITLE
Border and/or Shadow

### ISSUE THREAD

**Issue by ghost** [web-tiki/responsive-grid-of-hexagons#30]
I have tried adding a box-shadow / border to the hexagons and understand this is probably not the simplest task to achieve. Any chance you can figure out how to do this or edit the documentation?

**Comment by web-tiki** [comment]
Hello @jayhybrid this has already been discussed in issue #25  and issue #16 
It is not the easiest thing to do but it is achievable. Issue #25 describes an approach to achieve a border on the hexagons.

I am closing this issue as it isn't an issue with the grid but rather an alternate layout.

**Comment by ghost** [comment]
Thank you for your reply. Since this topic is very important to me and this repository seems to be the only good hexagon grid available, please consider adding this to your documentation:

filter: drop-shadow(0 0 0.2vw #555555);

This allowed me to simply add a shadow. I understand this may not be best practise and only works in modern browsers but for me it worked, and thats all that counts to me. Maybe it will help others too.

**Comment by web-tiki** [comment]
@jayhybrid thank you for the info and happy you found a solution to your issue.
