### ISSUE TITLE
Show h1 underneath image

### ISSUE THREAD

**Issue by skristyn** [web-tiki/responsive-grid-of-hexagons#32]
Hi - thank you so much for posting this!  I'm trying to customize it, and I'd like the h1 to always display below each hexagon, rather than sliding up in the middle on hover. 
I have it placed where I want and removed the animation, but because of the `overflow: hidden` property of the elements that contain it, the text is entirely invisible when moved outside the hexagon. Is there a way you'd recommend getting it to show up?

**Comment by skristyn** [comment]
Placed the header inside .hex but outside of .hexIn
then floated the header and used absolute positioning

**Comment by web-tiki** [comment]
@skristyn great if you managed to find a solution to your issue :)
