### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by ghost** [web-tiki/responsive-grid-of-hexagons#36]
I've been working a lot with CSS grid and I'm considering to make some contributions in the future to make the code more flexible when changes are needed and relying more an stuff like `calc()` which might help resolve issues like #35 and custom css properties

**Comment by poi33** [comment]
We don't have any contribution guidlines or simular, but if you manage to make the code easier to read or improve it we would love a contribution. If you mange to solve #35 that would be a good contribution to the project. 
If you question is if this is still maintained? Well i still look at all issues reported, @web-tiki you still active on github?

**Comment by poi33** [comment]
Was just reading up on calc and it seems its poorly supported in IE11. We might not want to support that anymore since its becoming an older browser, but what browser support we are going for is up to the owner of the repo.

**Comment by ghost** [comment]
~~Well as far as I know Flexbox is not supported in IE11 either so it's already not supported as far as I'm concerned.~~

I just did some checking and apparantly it is via a vendor prefix: https://caniuse.com/?search=display%3A%20flex and by enabling `layout.css.flexbox.enabled`. Which basically means it's only working for devs and not for end users.

**Comment by web-tiki** [comment]
Just to make sure you saw, there already is a branch using css grid here : https://github.com/web-tiki/responsive-grid-of-hexagons/tree/css-grid
I would like to keep the flexbox and css-grid versions in this repo for now. 
If you have some improvements to make on the css-grid version, you are more than welcome to do so and make a PR.

`calc()` has better browser support than css-grid so using it for that version won't change much regarding browser support.

**Comment by web-tiki** [comment]
@jayhybrid I will now close this tickety as it doesn't address a specific issue. 
Feel free to open another one if you find a specific issue.
