### ISSUE TITLE
Small jitter in on grid hover

### ISSUE THREAD

**Issue by poi33** [web-tiki/responsive-grid-of-hexagons#5]
# small movment on grid-item hover

There is a small movment on the image when hovering a grid item.

![grid_move](https://cloud.githubusercontent.com/assets/3340349/11913934/6b7d50a6-a674-11e5-85d8-d14b35389f3b.gif)

Above preview browser: Firefox 43.
Not present in Chrome 47.
Edge: (surprisingly) not in Edge 20.

**Comment by web-tiki** [comment]
@poi33 Can you retest on demo page please. It should be solved with latest merge.

**Comment by poi33** [comment]
No more image jitter on firefox
